version: 2.1

orbs:
  go: venus/go-pkg-test@1.0.1
jobs:
  test_all:
    executor:
      name: go/default
      tag: "cimg/go:1.18.1"
    steps:
      - go/setup_env:
          install_ffi: true
      - go/test:
          display-name: integrate_test
          suite: "integrate_test"
          target: "./integrate_test/..."
      - go/test:
          display-name: proofevent_uint_test
          suite: "proofevent"
          target: "./proofevent/..."
      - go/test:
          display-name: walletevent_uint_test
          suite: "walletevent"
          target: "./walletevent/..."
      - go/test:
          display-name: marketevent_uint_test
          suite: "marketevent"
          target: "./marketevent/..."
      - go/test:
          display-name: validator_unit_test
          suite: "validator_unit_test"
          target: "./validator/..."
      - go/test:
          display-name: baseevent_unit_test
          suite: "baseevent_unit_test"
          target: "./types/..."

workflows:
  ci:
    jobs:
      - test_all
